name: Checkout | Build | Artifact

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  Checkout_Build_Artifact:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        working-directory: ./app/
        run: mvn clean install
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
        # Artifact name
          name: AppArtifact
          path: app/target/verademo.war
