name: Verademo Static

on: [push]

jobs:
  build-sast:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify
     
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - name: Unzip the Pipeline Scanner2
      run: unzip pipeline-scan-LATEST.zip /y
    - name: Run Pipeline Scanner
      run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "/home/runner/work/JavaVeraDemo/JavaVeraDemo/target/verademo.war" --fail_on_severity="Very High, High"
